spring:
  data:
    mongodb:
      database: mongoDb

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.est0y.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
