version: "3.9"
services:
  mongo:
    hostname: mongo
    container_name: localmongo2
    image: mongo:5.0
    expose:
      - 27017
    ports:
      - 30002:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]